export const dietTypes = [
    {value:'lactoVegetarian' , label:'Lacto Vegetarian'},
    {value:'vegan' , label:'Vegan'},
    {value:'vegetarian' , label:'Vegetarian'},
    {value:'lowCarb' , label:'Low Carb'},
    {value:'mediterranean' , label:'Mediterranean'},
    {value:'keto' , label:'Keto'},
    {value:'glutenFree' , label:'Gluten free'},
    {value:'dairyFree' , label:'Dairy free'},
]
export const cuisineTypes = [
    {value:'african' , label:'African'},
    {value:'american' , label:'American'},
    {value:'asian' , label:'Asian'},
    {value:'australian' , label:'Australian'},
    {value:'british' , label:'British'},
    {value:'canadian' , label:'Canadian'},
    {value:'caribbean' , label:'Caribbean'},
    {value:'chinese' , label:'Chinese'},
    {value:'cuban' , label:'Cuban'},
    {value:'eastern-european' , label:'Eastern European'},
    {value:'european' , label:'European'},
    {value:'latin-american' , label:'Latin American'},
    {value:'mediterranean' , label:'Mediterranean'},
    {value:'mexican' , label:'Mexican'},
    {value:'middle-eastern' , label:'Middle Eastern'},
]
export const mealTypes = [
    {value:'aperitif' , label:'Aperitif'},
    {value:'appetizers' , label:'Appetizers'},
    {value:'beverages' , label:'Beverages'},
    {value:'breads' , label:'Breads'},
    {value:'breakfast' , label:'Breakfast'},
    {value:'lunch' , label:'Lunch'},
    {value:'cocktails' , label:'Cocktails'},
]